### ISSUE TITLE
Dropbox preview link not working

### ISSUE THREAD

**Issue by LSgeo** [L7c8ana/Fast-RCNN-Geo#1]
Hi, I'm attempting to explore your code and model. I'm trying to download your pretrained model at https://www.dropbox.com/h?preview=net-deployedGeo.mat, however I don't think sharing has been correctly enabled, or the link is broken somehow. 

Please let me know if that link will allow public viewing access, so I can download and use your model.

Kind regards,
Luke

**Comment by L7c8ana** [comment]
Thanks Luke,
I changed the link to Geo Model at Github.

________________________________
De: Luke <notifications@github.com>
Enviado: terça-feira, 10 de março de 2020 08:59
Para: L7c8ana/Fast-RCNN-Geo <Fast-RCNN-Geo@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [L7c8ana/Fast-RCNN-Geo] Dropbox preview link not working (#1)


Hi, I'm attempting to explore your code and model. I'm trying to download your pretrained model at https://www.dropbox.com/h?preview=net-deployedGeo.mat, however I don't think sharing has been correctly enabled, or the link is broken somehow.

Please let me know if that link will allow public viewing access, so I can download and use your model.

Kind regards,
Luke

**Comment by LSgeo** [comment]
Thanks, and congratulations on the paper and interesting project.
